# Generated by Django 4.0.3 on 2022-04-09 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaster_volunteer', to='disaster.disaster')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='missing')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaster_report', to='disaster.disaster')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaster_donation', to='disaster.disaster')),
            ],
        ),
    ]
