# Generated by Django 4.0.3 on 2022-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
