# Generated by Django 4.0.3 on 2022-04-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0004_organization_donation_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='organization',
        ),
    ]
