# Generated by Django 4.0.3 on 2022-04-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0005_remove_donation_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_donation', to='disaster.organization'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_volunteer', to='disaster.organization'),
        ),
    ]
