# Generated by Django 4.0.3 on 2022-04-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0007_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='attempts',
        ),
    ]
