# Generated by Django 4.0.3 on 2022-04-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0008_remove_order_amount_due_remove_order_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
