# Generated by Django 4.0.3 on 2022-04-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0009_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
