# Generated by Django 4.0.3 on 2022-04-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0010_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
