# Generated by Django 4.0.3 on 2022-04-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0011_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt',
        ),
    ]
